### (reminder to self: show the slide first)

In [2]:
import numpy as np
import random

In [12]:
x = np.random.randn(10000)
x[:5]

array([-1.442928  ,  0.6071328 ,  0.66751396, -2.37045438, -2.00907059])

In [13]:
x.dtype

dtype('float64')

In [14]:
# cast np array x to python list xl:

xl = list(x)
xl[:5]

[-1.44292799895912,
 0.6071328027982574,
 0.6675139596563933,
 -2.3704543800109574,
 -2.0090705942486933]

Compare element-wise multiplication in python and numpy:

In [15]:
%%timeit
x * x

3.26 µs ± 225 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


this is even doing less and is still 100x slower:

In [16]:
%%timeit

for i in xl:
    i * i

913 µs ± 40.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Vectorize your code!
* runs faster
* makes for concise code that is (usually) easy to read


### indexing

In [6]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([5, 6, 7, 8, 9])

In [9]:
arr[1:3]

array([1, 2])

In [10]:
arr[2:-2]

array([2, 3, 4, 5, 6, 7])

In [11]:
arr[::2]

array([0, 2, 4, 6, 8])

In [12]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
arr < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [14]:
arr[arr < 4]

array([0, 1, 2, 3])

### matrix multiplication

In [15]:
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)


In [16]:
a * b

ValueError: operands could not be broadcast together with shapes (5,3) (3,2) 

In [17]:
np.dot(a, b)

array([[1.18886323, 0.85167412],
       [0.69132077, 0.55869093],
       [0.57016627, 0.70870708],
       [1.35638108, 0.90653991],
       [1.18157308, 0.88038129]])

In [18]:
a @ b  # for newer versions of python (which you should be using)
assert np.array_equal(a @ b, np.dot(a, b))

### A few useful numpy functions

In [30]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [34]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [14]:
z = np.random.randn(500, 10)

print('means')
print(z.mean(0))

print()
print('variance')
print(z.var(0))

means
[ 0.09219057 -0.07997817  0.00594129  0.01292845 -0.02573719  0.03692442
 -0.03650778 -0.08611321  0.00152045  0.06864385]

variance
[1.07264922 0.97661327 0.97542888 1.00028603 0.99051005 0.97876361
 0.99297789 1.02407552 0.96730572 0.97152496]


In [37]:
z.max(0)

array([3.20823566, 3.01227803, 3.01969138, 3.49240339, 3.16626128,
       2.6226179 , 2.5771921 , 3.66611077, 2.29943785, 3.03424321])

There are many more and it is worth learning them.

Don't reimplement numpy/scipy functions, you will just wind up with buggy & slow versions of them