In [1]:
import numpy as np

## Python is dynamically typed:

In [2]:
l = ['a', 1, None, str, np]

### this makes thing like `for` loops very slow

`numpy` gives access to optimized procedures, implemented in low-level language (eg `C`)

In [3]:
x = np.random.randn(10000)

In [4]:
x[:5]

array([ 0.32795668, -0.14876166,  0.59299705, -0.10451492, -0.87029294])

In [5]:
x.dtype

dtype('float64')

In [6]:
# cast np array x to python list xl:

xl = list(x)
xl[:5]

[0.32795667604431317,
 -0.14876166074985095,
 0.5929970489829097,
 -0.10451492216981852,
 -0.8702929439453454]

### Square each element in list:

native python `for` loop is very slow:

In [7]:
%%timeit

for i in xl:
    i * i

886 µs ± 44.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


`numpy` multiplication is much faster!

In [8]:
%%timeit

x * x  # short hand for np.multiply(x, x)

3.53 µs ± 159 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Vectorize your code!
* runs faster
* makes for concise code that is (usually) easier to read


### indexing

In [9]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[::-1]  # etc ..

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

boolean masks

In [12]:
arr < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [13]:
arr[arr < 4]

array([0, 1, 2, 3])

### matrix multiplication

In [14]:
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)


In [15]:
a.shape

(5, 3)

In [16]:
a * b

ValueError: operands could not be broadcast together with shapes (5,3) (3,2) 

In [ ]:
(a @ b).shape

In [ ]:
np.dot(a, b)

In [ ]:
a @ b  # for newer versions of python (which you should be using!)
assert np.array_equal(a @ b, np.dot(a, b))

### A few useful numpy functions

In [ ]:
np.arange(5)

In [ ]:
np.arange(0, 5, 0.5)

In [ ]:
np.linspace(0, 5, 11)

In [ ]:
z = np.random.randn(500, 10)

print('means')
print(z.mean(0))

print()
print('variance')
print(z.var(0))

In [ ]:
z.max(0)

In [ ]:
np.unique(a)

There are many more and it is worth learning them.

Don't reimplement numpy/scipy functions, you will just wind up with buggy & slow versions of them